name: karaoke-bot
channels:
  - conda-forge
dependencies:
  - python=3.12.1  # Specify the Python version if needed
  - python-telegram-bot
  - pandas
  - typing_extensions  # If you need the `typing` module, use `typing_extensions` for versions beyond Python 3.5
  - functools
  - musicbrainzngs